### ISSUE TITLE
我觉得这种方式不太方便

### ISSUE THREAD

**Issue by ihewro** [typecho-fans/themes#1]
每个作者都有自己项目地址，再传到这里，每次更新主题，都需要两边都同步，似乎有点麻烦。

不妨可以再readme.md中直接导向作者的原项目地址，这样比较方便，也能获得最新的版本主题。

对于没有github项目的主题，可以传到这里，单开一个文件夹。

已经有github项目，就没有必要了，个人看法。

**Comment by nexmoe** [comment]
我竟然连github都不想更新

**Comment by kirainmoe** [comment]
+1. 而且这样想要下载一个主题就要把这个 repo 都打包下载不觉得很没必要么……

**Comment by thxplus** [comment]
其实还是要靠官方发布各作品GitHub目录比较靠谱 这个基本意义不大
2017年3月5日 21:11于 吟夢ちゃん <notifications@github.com>写道：+1. 而且这样想要下载一个主题就要把这个 repo 都打包下载不觉得很没必要么……

**Comment by chekun** [comment]
看来 。。。  [chekun/AppStore](/chekun/AppStore) 需要加入主题功能 😃

**Comment by thxplus** [comment]
主要是基本没有官方。。。我们都是流民。官方应该有作者作品目录才对。。
2017年3月5日 21:21于 Che Kun <notifications@github.com>写道：看来 。。。  chekun/AppStore 需要加入主题功能 😃

**Comment by bestony** [comment]
使用 Git  Submodule 试试？

**Comment by kokororin** [comment]
直接面向Markdown编程就好（只要提供一个链接连接到作者的repo），submodule的意义也不是很大，而且也很麻烦

**Comment by hongweipeng** [comment]
我觉得再讨论下去的结果就是弄个主题模板展示的网站了

**Comment by Dalodd** [comment]
也可以写个主题市场的插件

**Comment by jzwalk** [comment]
用submodule做个目录链接很简单的，见[**typecho-fans/plugins**](https://github.com/typecho-fans/plugins)下.gitmodules文件。但它打包是下载不到。

其实这种组织目录主要是为了方便商店型插件集中读取并选择在线安装，目前chekun的[**AppStore**](https://github.com/typecho-fans/plugins/tree/master/AppStore)只做了插件功能，主题这边还有待开发。

自己的repo别人想帮忙得提交pull request，万一你离开不管了有人想接手还是得另传一份。所以长期看还是subtree推送好，当然嫌麻烦就submodule链接下也没问题，用户都会去点击另存

**Comment by umehina** [comment]
@Dalodd 我印象中主题市场好像有人做了吧
