### ISSUE TITLE
导航栏在手机端bug

### ISSUE THREAD

**Issue by yyqyu** [typecho-fans/themes#5]
手机端的导航栏有BUG，出不来

**Comment by hongweipeng** [comment]
哪个主题？

**Comment by yyqyu** [comment]
绿葡萄呀

发自我的 iPhone

在 2018年11月12日，09:22，HongWeipeng <notifications@github.com<mailto:notifications@github.com>> 写道：


哪个主题？

**Comment by hongweipeng** [comment]
确实存在这个问题，现已修复完毕。谢谢反馈。

**Comment by yyqyu** [comment]
重新发布了吗？


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: HongWeipeng <notifications@github.com>
发送时间: Thursday, November 15, 2018 4:09:48 PM
收件人: typecho-fans/themes
抄送: 杨永强; Author
主题: Re: [typecho-fans/themes] 导航栏在手机端bug (#5)


确实存在这个问题，现已修复完毕。谢谢反馈。

―

**Comment by hongweipeng** [comment]
更新到仓库了。

**Comment by hongweipeng** [comment]
好像引发了其他问题- -。我得处理下。

**Comment by yyqyu** [comment]
好的，修复好了喊我一声

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: HongWeipeng <notifications@github.com>
发送时间: Thursday, November 15, 2018 4:19:21 PM
收件人: typecho-fans/themes
抄送: 杨永强; Author
主题: Re: [typecho-fans/themes] 导航栏在手机端bug (#5)


好像引发了其他问题- -。我得处理下。

―

**Comment by hongweipeng** [comment]
ok了
